/*
 * Generated by JasperReports - 04/09/17 17:15
 */
import net.sf.jasperreports.engine.*;
import net.sf.jasperreports.engine.fill.*;

import java.util.*;
import java.math.*;
import java.text.*;
import java.io.*;
import java.net.*;

import net.sf.jasperreports.engine.*;
import java.util.*;
import com.sankhya.util.StringUtils;
import net.sf.jasperreports.engine.data.*;


/**
 *
 */
public class PEDIDO_DE_VENDA_1504556121782_518313 extends JREvaluator
{


    /**
     *
     */
    private JRFillParameter parameter_IS_IGNORE_PAGINATION = null;
    private JRFillParameter parameter_REPORT_CONNECTION = null;
    private JRFillParameter parameter_FILTER = null;
    private JRFillParameter parameter_PDIR_MODELO = null;
    private JRFillParameter parameter_JASPER_REPORT = null;
    private JRFillParameter parameter_REPORT_LOCALE = null;
    private JRFillParameter parameter_REPORT_TIME_ZONE = null;
    private JRFillParameter parameter_REPORT_TEMPLATES = null;
    private JRFillParameter parameter_SUBREPORT_DIR = null;
    private JRFillParameter parameter_REPORT_MAX_COUNT = null;
    private JRFillParameter parameter_REPORT_SCRIPTLET = null;
    private JRFillParameter parameter_JASPER_REPORTS_CONTEXT = null;
    private JRFillParameter parameter_REPORT_FILE_RESOLVER = null;
    private JRFillParameter parameter_REPORT_FORMAT_FACTORY = null;
    private JRFillParameter parameter_REPORT_PARAMETERS_MAP = null;
    private JRFillParameter parameter_REPORT_RESOURCE_BUNDLE = null;
    private JRFillParameter parameter_REPORT_DATA_SOURCE = null;
    private JRFillParameter parameter_NUNOTA = null;
    private JRFillParameter parameter_REPORT_CONTEXT = null;
    private JRFillParameter parameter_REPORT_CLASS_LOADER = null;
    private JRFillParameter parameter_REPORT_URL_HANDLER_FACTORY = null;
    private JRFillParameter parameter_REPORT_VIRTUALIZER = null;
    private JRFillParameter parameter_SORT_FIELDS = null;
    private JRFillField field_ZONA = null;
    private JRFillField field_NOMEPARC = null;
    private JRFillField field_NUMNOTA = null;
    private JRFillField field_CODPARC = null;
    private JRFillField field_CODVEND = null;
    private JRFillField field_VENDEDOR = null;
    private JRFillField field_INSCESTADNAUF = null;
    private JRFillField field_NOMEEND = null;
    private JRFillField field_UF = null;
    private JRFillField field_DESCRICAO = null;
    private JRFillField field_VLRDESCTOT = null;
    private JRFillField field_NUNOTA = null;
    private JRFillField field_OBSERVACAO = null;
    private JRFillField field_CGC_CPF = null;
    private JRFillField field_CODEMP = null;
    private JRFillField field_NOMEBAI = null;
    private JRFillField field_TELEFONE = null;
    private JRFillField field_VLRDESCSERV = null;
    private JRFillField field_VLRDESCTOTITEM = null;
    private JRFillField field_RAZAOEMP = null;
    private JRFillField field_DESCROPER = null;
    private JRFillField field_RAZAOSOCIAL = null;
    private JRFillField field_CEP = null;
    private JRFillField field_LOGODANFE = null;
    private JRFillField field_NOMECID = null;
    private JRFillField field_VLRNOTA = null;
    private JRFillField field_FAX = null;
    private JRFillField field_NUMEND = null;
    private JRFillVariable variable_PAGE_NUMBER = null;
    private JRFillVariable variable_COLUMN_NUMBER = null;
    private JRFillVariable variable_REPORT_COUNT = null;
    private JRFillVariable variable_PAGE_COUNT = null;
    private JRFillVariable variable_COLUMN_COUNT = null;
    private JRFillVariable variable_NUMNOTA_COUNT = null;
    private JRFillVariable variable_CODPARC_COUNT = null;
    private JRFillVariable variable_TOTAL_SERVICO = null;
    private JRFillVariable variable_TOTAL_PRODUTO = null;
    private JRFillVariable variable_DESCONTO_TOTAL = null;
    private JRFillVariable variable_VALOR_LIQUIDO = null;


    /**
     *
     */
    public void customizedInit(
        Map pm,
        Map fm,
        Map vm
        )
    {
        initParams(pm);
        initFields(fm);
        initVars(vm);
    }


    /**
     *
     */
    private void initParams(Map pm)
    {
        parameter_IS_IGNORE_PAGINATION = (JRFillParameter)pm.get("IS_IGNORE_PAGINATION");
        parameter_REPORT_CONNECTION = (JRFillParameter)pm.get("REPORT_CONNECTION");
        parameter_FILTER = (JRFillParameter)pm.get("FILTER");
        parameter_PDIR_MODELO = (JRFillParameter)pm.get("PDIR_MODELO");
        parameter_JASPER_REPORT = (JRFillParameter)pm.get("JASPER_REPORT");
        parameter_REPORT_LOCALE = (JRFillParameter)pm.get("REPORT_LOCALE");
        parameter_REPORT_TIME_ZONE = (JRFillParameter)pm.get("REPORT_TIME_ZONE");
        parameter_REPORT_TEMPLATES = (JRFillParameter)pm.get("REPORT_TEMPLATES");
        parameter_SUBREPORT_DIR = (JRFillParameter)pm.get("SUBREPORT_DIR");
        parameter_REPORT_MAX_COUNT = (JRFillParameter)pm.get("REPORT_MAX_COUNT");
        parameter_REPORT_SCRIPTLET = (JRFillParameter)pm.get("REPORT_SCRIPTLET");
        parameter_JASPER_REPORTS_CONTEXT = (JRFillParameter)pm.get("JASPER_REPORTS_CONTEXT");
        parameter_REPORT_FILE_RESOLVER = (JRFillParameter)pm.get("REPORT_FILE_RESOLVER");
        parameter_REPORT_FORMAT_FACTORY = (JRFillParameter)pm.get("REPORT_FORMAT_FACTORY");
        parameter_REPORT_PARAMETERS_MAP = (JRFillParameter)pm.get("REPORT_PARAMETERS_MAP");
        parameter_REPORT_RESOURCE_BUNDLE = (JRFillParameter)pm.get("REPORT_RESOURCE_BUNDLE");
        parameter_REPORT_DATA_SOURCE = (JRFillParameter)pm.get("REPORT_DATA_SOURCE");
        parameter_NUNOTA = (JRFillParameter)pm.get("NUNOTA");
        parameter_REPORT_CONTEXT = (JRFillParameter)pm.get("REPORT_CONTEXT");
        parameter_REPORT_CLASS_LOADER = (JRFillParameter)pm.get("REPORT_CLASS_LOADER");
        parameter_REPORT_URL_HANDLER_FACTORY = (JRFillParameter)pm.get("REPORT_URL_HANDLER_FACTORY");
        parameter_REPORT_VIRTUALIZER = (JRFillParameter)pm.get("REPORT_VIRTUALIZER");
        parameter_SORT_FIELDS = (JRFillParameter)pm.get("SORT_FIELDS");
    }


    /**
     *
     */
    private void initFields(Map fm)
    {
        field_ZONA = (JRFillField)fm.get("ZONA");
        field_NOMEPARC = (JRFillField)fm.get("NOMEPARC");
        field_NUMNOTA = (JRFillField)fm.get("NUMNOTA");
        field_CODPARC = (JRFillField)fm.get("CODPARC");
        field_CODVEND = (JRFillField)fm.get("CODVEND");
        field_VENDEDOR = (JRFillField)fm.get("VENDEDOR");
        field_INSCESTADNAUF = (JRFillField)fm.get("INSCESTADNAUF");
        field_NOMEEND = (JRFillField)fm.get("NOMEEND");
        field_UF = (JRFillField)fm.get("UF");
        field_DESCRICAO = (JRFillField)fm.get("DESCRICAO");
        field_VLRDESCTOT = (JRFillField)fm.get("VLRDESCTOT");
        field_NUNOTA = (JRFillField)fm.get("NUNOTA");
        field_OBSERVACAO = (JRFillField)fm.get("OBSERVACAO");
        field_CGC_CPF = (JRFillField)fm.get("CGC_CPF");
        field_CODEMP = (JRFillField)fm.get("CODEMP");
        field_NOMEBAI = (JRFillField)fm.get("NOMEBAI");
        field_TELEFONE = (JRFillField)fm.get("TELEFONE");
        field_VLRDESCSERV = (JRFillField)fm.get("VLRDESCSERV");
        field_VLRDESCTOTITEM = (JRFillField)fm.get("VLRDESCTOTITEM");
        field_RAZAOEMP = (JRFillField)fm.get("RAZAOEMP");
        field_DESCROPER = (JRFillField)fm.get("DESCROPER");
        field_RAZAOSOCIAL = (JRFillField)fm.get("RAZAOSOCIAL");
        field_CEP = (JRFillField)fm.get("CEP");
        field_LOGODANFE = (JRFillField)fm.get("LOGODANFE");
        field_NOMECID = (JRFillField)fm.get("NOMECID");
        field_VLRNOTA = (JRFillField)fm.get("VLRNOTA");
        field_FAX = (JRFillField)fm.get("FAX");
        field_NUMEND = (JRFillField)fm.get("NUMEND");
    }


    /**
     *
     */
    private void initVars(Map vm)
    {
        variable_PAGE_NUMBER = (JRFillVariable)vm.get("PAGE_NUMBER");
        variable_COLUMN_NUMBER = (JRFillVariable)vm.get("COLUMN_NUMBER");
        variable_REPORT_COUNT = (JRFillVariable)vm.get("REPORT_COUNT");
        variable_PAGE_COUNT = (JRFillVariable)vm.get("PAGE_COUNT");
        variable_COLUMN_COUNT = (JRFillVariable)vm.get("COLUMN_COUNT");
        variable_NUMNOTA_COUNT = (JRFillVariable)vm.get("NUMNOTA_COUNT");
        variable_CODPARC_COUNT = (JRFillVariable)vm.get("CODPARC_COUNT");
        variable_TOTAL_SERVICO = (JRFillVariable)vm.get("TOTAL_SERVICO");
        variable_TOTAL_PRODUTO = (JRFillVariable)vm.get("TOTAL_PRODUTO");
        variable_DESCONTO_TOTAL = (JRFillVariable)vm.get("DESCONTO_TOTAL");
        variable_VALOR_LIQUIDO = (JRFillVariable)vm.get("VALOR_LIQUIDO");
    }


    /**
     *
     */
    public Object evaluate(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "./"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "/home/mgeweb/modelos/relatorios/propostadevenda"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)field_NUMNOTA.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.Integer)field_NUNOTA.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_RAZAOEMP.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_VENDEDOR.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new Date(); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getValue())+"-"+((java.lang.String)field_NOMEPARC.getValue()) + (((java.lang.String)field_RAZAOSOCIAL.getValue()) == null ? "" : " / " + ((java.lang.String)field_RAZAOSOCIAL.getValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_TELEFONE.getValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = StringUtils.formataCgcCpf(((java.lang.String)field_CGC_CPF.getValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)field_INSCESTADNAUF.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)field_NOMEEND.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)field_NOMECID.getValue())+" - "+((java.lang.String)field_UF.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = StringUtils.formataCep(((java.lang.String)field_CEP.getValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)field_NOMEBAI.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_FAX.getValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = "Proposta de Venda"; //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = "/users/adriano/relatorios/propvenda/ITENS_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = "Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()) + " de "; //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = "" + ((java.lang.Integer)variable_PAGE_NUMBER.getValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_SERVICO.getValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_PRODUTO.getValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.math.BigDecimal)variable_DESCONTO_TOTAL.getValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.math.BigDecimal)variable_VALOR_LIQUIDO.getValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_OBSERVACAO.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = "/users/adriano/relatorios/propvenda/FINAN_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = "/users/adriano/relatorios/propvenda/RODAPE_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "Essa proposta é válida por 07 dias, contados a partir da data de envio."; //$JR_EXPR_ID=49$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateOld(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "./"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "/home/mgeweb/modelos/relatorios/propostadevenda"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)field_NUMNOTA.getOldValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.Integer)field_NUNOTA.getOldValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_RAZAOEMP.getOldValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_VENDEDOR.getOldValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new Date(); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getOldValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getOldValue())+"-"+((java.lang.String)field_NOMEPARC.getOldValue()) + (((java.lang.String)field_RAZAOSOCIAL.getOldValue()) == null ? "" : " / " + ((java.lang.String)field_RAZAOSOCIAL.getOldValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_TELEFONE.getOldValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = StringUtils.formataCgcCpf(((java.lang.String)field_CGC_CPF.getOldValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)field_INSCESTADNAUF.getOldValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)field_NOMEEND.getOldValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)field_NOMECID.getOldValue())+" - "+((java.lang.String)field_UF.getOldValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = StringUtils.formataCep(((java.lang.String)field_CEP.getOldValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)field_NOMEBAI.getOldValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_FAX.getOldValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = "Proposta de Venda"; //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = "/users/adriano/relatorios/propvenda/ITENS_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = "Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()) + " de "; //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = "" + ((java.lang.Integer)variable_PAGE_NUMBER.getOldValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_SERVICO.getOldValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_PRODUTO.getOldValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.math.BigDecimal)variable_DESCONTO_TOTAL.getOldValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.math.BigDecimal)variable_VALOR_LIQUIDO.getOldValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_OBSERVACAO.getOldValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = "/users/adriano/relatorios/propvenda/FINAN_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = "/users/adriano/relatorios/propvenda/RODAPE_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "Essa proposta é válida por 07 dias, contados a partir da data de envio."; //$JR_EXPR_ID=49$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


    /**
     *
     */
    public Object evaluateEstimated(int id) throws Throwable
    {
        Object value = null;

        switch (id)
        {
            case 0 : 
            {
                value = "./"; //$JR_EXPR_ID=0$
                break;
            }
            case 1 : 
            {
                value = "/home/mgeweb/modelos/relatorios/propostadevenda"; //$JR_EXPR_ID=1$
                break;
            }
            case 2 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=2$
                break;
            }
            case 3 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=3$
                break;
            }
            case 4 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=4$
                break;
            }
            case 5 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=5$
                break;
            }
            case 6 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=6$
                break;
            }
            case 7 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=7$
                break;
            }
            case 8 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=8$
                break;
            }
            case 9 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=9$
                break;
            }
            case 10 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=10$
                break;
            }
            case 11 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=11$
                break;
            }
            case 12 : 
            {
                value = new java.lang.Integer(1); //$JR_EXPR_ID=12$
                break;
            }
            case 13 : 
            {
                value = new java.lang.Integer(0); //$JR_EXPR_ID=13$
                break;
            }
            case 14 : 
            {
                value = ((java.lang.Integer)field_NUMNOTA.getValue()); //$JR_EXPR_ID=14$
                break;
            }
            case 15 : 
            {
                value = ((java.lang.Integer)field_NUNOTA.getValue()); //$JR_EXPR_ID=15$
                break;
            }
            case 16 : 
            {
                value = ((java.lang.String)field_RAZAOEMP.getValue()); //$JR_EXPR_ID=16$
                break;
            }
            case 17 : 
            {
                value = ((java.lang.String)field_VENDEDOR.getValue()); //$JR_EXPR_ID=17$
                break;
            }
            case 18 : 
            {
                value = new Date(); //$JR_EXPR_ID=18$
                break;
            }
            case 19 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getValue()); //$JR_EXPR_ID=19$
                break;
            }
            case 20 : 
            {
                value = ((java.lang.Integer)field_CODPARC.getValue())+"-"+((java.lang.String)field_NOMEPARC.getValue()) + (((java.lang.String)field_RAZAOSOCIAL.getValue()) == null ? "" : " / " + ((java.lang.String)field_RAZAOSOCIAL.getValue())); //$JR_EXPR_ID=20$
                break;
            }
            case 21 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_TELEFONE.getValue())); //$JR_EXPR_ID=21$
                break;
            }
            case 22 : 
            {
                value = StringUtils.formataCgcCpf(((java.lang.String)field_CGC_CPF.getValue())); //$JR_EXPR_ID=22$
                break;
            }
            case 23 : 
            {
                value = ((java.lang.String)field_INSCESTADNAUF.getValue()); //$JR_EXPR_ID=23$
                break;
            }
            case 24 : 
            {
                value = ((java.lang.String)field_NOMEEND.getValue()); //$JR_EXPR_ID=24$
                break;
            }
            case 25 : 
            {
                value = ((java.lang.String)field_NOMECID.getValue())+" - "+((java.lang.String)field_UF.getValue()); //$JR_EXPR_ID=25$
                break;
            }
            case 26 : 
            {
                value = StringUtils.formataCep(((java.lang.String)field_CEP.getValue())); //$JR_EXPR_ID=26$
                break;
            }
            case 27 : 
            {
                value = ((java.lang.String)field_NOMEBAI.getValue()); //$JR_EXPR_ID=27$
                break;
            }
            case 28 : 
            {
                value = StringUtils.formataTelefone2(((java.lang.String)field_FAX.getValue())); //$JR_EXPR_ID=28$
                break;
            }
            case 29 : 
            {
                value = "Proposta de Venda"; //$JR_EXPR_ID=29$
                break;
            }
            case 30 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=30$
                break;
            }
            case 31 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=31$
                break;
            }
            case 32 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=32$
                break;
            }
            case 33 : 
            {
                value = "/users/adriano/relatorios/propvenda/ITENS_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=33$
                break;
            }
            case 34 : 
            {
                value = "Página " + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()) + " de "; //$JR_EXPR_ID=34$
                break;
            }
            case 35 : 
            {
                value = "" + ((java.lang.Integer)variable_PAGE_NUMBER.getEstimatedValue()); //$JR_EXPR_ID=35$
                break;
            }
            case 36 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_SERVICO.getEstimatedValue()); //$JR_EXPR_ID=36$
                break;
            }
            case 37 : 
            {
                value = ((java.math.BigDecimal)variable_TOTAL_PRODUTO.getEstimatedValue()); //$JR_EXPR_ID=37$
                break;
            }
            case 38 : 
            {
                value = ((java.math.BigDecimal)variable_DESCONTO_TOTAL.getEstimatedValue()); //$JR_EXPR_ID=38$
                break;
            }
            case 39 : 
            {
                value = ((java.math.BigDecimal)variable_VALOR_LIQUIDO.getEstimatedValue()); //$JR_EXPR_ID=39$
                break;
            }
            case 40 : 
            {
                value = ((java.lang.String)field_OBSERVACAO.getValue()); //$JR_EXPR_ID=40$
                break;
            }
            case 41 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=41$
                break;
            }
            case 42 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=42$
                break;
            }
            case 43 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=43$
                break;
            }
            case 44 : 
            {
                value = "/users/adriano/relatorios/propvenda/FINAN_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=44$
                break;
            }
            case 45 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=45$
                break;
            }
            case 46 : 
            {
                value = ((java.math.BigDecimal)parameter_NUNOTA.getValue()); //$JR_EXPR_ID=46$
                break;
            }
            case 47 : 
            {
                value = ((java.sql.Connection)parameter_REPORT_CONNECTION.getValue()); //$JR_EXPR_ID=47$
                break;
            }
            case 48 : 
            {
                value = "/users/adriano/relatorios/propvenda/RODAPE_PEDIDO_DE_VENDA.jasper"; //$JR_EXPR_ID=48$
                break;
            }
            case 49 : 
            {
                value = "Essa proposta é válida por 07 dias, contados a partir da data de envio."; //$JR_EXPR_ID=49$
                break;
            }
           default :
           {
           }
        }
        
        return value;
    }


}
